apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: matanlevi201/expiration
          env:
            - name: QUEUE_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: QUEUE_URL
              value: "http://nats-srv:4222"
            - name: QUEUE_CLUSTER_ID
              value: ticket
            - name: REDIS_HOST
              value: expiration-redis-srv
