apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: eliyashlomo7/payments-service
          ports:
            - containerPort: 3000
          env:
            - name: QUEUE_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: QUEUE_URL
              value: "http://nats-srv:4222"
            - name: QUEUE_CLUSTER_ID
              value: ticket
            - name: DB_URI
              value: "mongodb://payments-mongo-srv:27017/payments"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
            - name: PUB_STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: public-stripe-secret
                  key: PUB_STRIPE_KEY
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
